//two string str1 and str2 is given then find that can str2 be generated by rotating 
// str1 by 2 places in either clockwise or anticlockwise direction.
//if yes print 1 else print 0


#include <iostream>
#include<string>
using namespace std;
//check if clockwise rotation is possible to generate str1 from str2..................................
int clockwise_rotate(string str2, string str1)
{
    int i,j,len=str1.size();
    if(str1[0]!=str2[len-2] || str1[1]!=str2[len-1])
    {
        return 0;
    }
    else
    {
        for(i=2,j=0;i<len && j<len-2;i++,j++)
        {
            if(str1[i]!=str2[j])
            {
                return 0;
            }
        }
        if(i==len) return 1;
    }
}

//check for anticlockwise rotation by 2 places......................................
int anticlockwise_rotate(string str1, string str2)
{
    int i,j,len=str1.size();
    if(str1[0]!=str2[len-2] || str1[1]!=str2[len-1])
    {
        return 0;
    }
    else
    {
        for(i=2,j=0;i<len && j<len-2;i++,j++)
        {
            if(str1[i]!=str2[j])
            {
                return 0;
            }
        }
        if(i==len) return 1;
    }
}

//
int str_rotate(string str1,string str2)
{
    int m,n;
    m=clockwise_rotate(str1,str2);
    n=anticlockwise_rotate(str1,str2);
    if(m||n) return 1;// if either way possible to generate return 1 else return 0............
    else return 0;
}


int main() {
	//code
	int t,i,p;
	cin>>t;
	string str1,str2;
	for(i=0;i<t;i++)
	{
	    cin>>str1;
	    cin>>str2;
	    p=str_rotate(str1,str2);
	    cout<<p<<endl;
	    
	}
	return 0;
}
